### ISSUE TITLE
Grunt + Bower

### ISSUE THREAD

**Issue by konstantinkrassmann** [amoilanen/jsAspect#10]
Because i am pretty familiar with those 2 tools, i could do this for us. 

Publish this lib on bower and add grunt support. 

What you want to get done with grunt ?

**Comment by amoilanen** [comment]
I wanted to add a Grunt build and it is in the TODO list https://github.com/antivanov/jsAspect/blob/master/TODO

The build should include the standard actions: code linting, minification, running tests, etc.

Also after the library is more or less complete I planned to publish it as a Node.js and Bower packages.

**Comment by amoilanen** [comment]
I plan to make further small modifications to the project before it can be published to NPM and then publish it there https://www.npmjs.org/~ant-ivanov. 

If you want you can test the package installation process and publish the package for Bower.
