### ISSUE TITLE
(#feat) Advice in constructor

### ISSUE THREAD

**Issue by konstantinkrassmann** [amoilanen/jsAspect#7]
Hi,
I have got 1 last problem: 

If i try to advice methods that are defined like this: 

``` javascript
function Parent()
    {
      this.method1 = function(){
        return "method1";
      }
}
```

I can't place join points inside the `method1`, because we just look on the prototype.

The only possibility to achieve this, is to completely copy the constructor (inherit).

``` javascript
//Method inject, otherwrite the target to intercept join points into embedded functions within target
 function newTarget(){}
 newTarget.prototype = new target();
```

But this destroys my old constructor and seems like a bad approach.

Is there another way to make this work ?

**Comment by amoilanen** [comment]
The actual method `method1` is not added to a created object until we call `new Parent()` and do create it. There is a special pointcut `jsAspect.POINTCUTS.METHODS` you can use. Example from tests:

``` javascript
  test("jsAspect.inject 'before' advice, last `context` argument contains method name", function() {
    var obj = {
      method1: function() {
        return "method1value";
      },
      method2: function() {
        return "method2value";
      }
    };
    var calledMethodNames = [];

    jsAspect.inject(obj, jsAspect.POINTCUT.METHODS, jsAspect.JOIN_POINT.BEFORE,
      function(context) {
        calledMethodNames.push(context.methodName);
      }
    );

    equal(obj.method1(), "method1value", "method1 executed");
    equal(obj.method2(), "method2value", "method2 executed");
    deepEqual(calledMethodNames, ["method1", "method2"], "Method name is available in context");
  });
```

Then you will be applying aspects to each created object individually when creating it. If you want to apply aspects once and for all objects that will be created subsequently, then `method1` should be moved to the prototype and the pointcut `jsAspect.POINTCUTS.PROTOTYPE_METHODS` can be used.
